name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: gradle

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew composeApp:assembleDebug

      - name: Upload all APKs
        uses: actions/upload-artifact@v4
        with:
         name: all-apks
         path: '**/build/outputs/apk/**/*.apk'
